blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://discord.gg/yUxrQwSJYY
    about: For any questions or general discussions - contact me through my channel on this discord server.